apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-app-of-apps-1
  labels:
    application: guestbook-app-of-apps-1
spec:
  project: customer
  source:
    repoURL: <YourRepositoryHere>
    targetRevision: <PathToYourBranch>
    path: <PathToYourApp>
  destination:
    namespace: example-namespace-1
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
